# Generated by Django 5.0 on 2023-12-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
