# Generated by Django 5.0 on 2023-12-27 20:02

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
    ]
