# Generated by Django 5.0 on 2023-12-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
