# Generated by Django 5.0 on 2024-01-04 17:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 17, 7, 37, 692073, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description has been added'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
